version: "3"

services:
  postgres:
    image: postgres:15.4-bookworm
    container_name: fastapi-hatch-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: trusted_user
      POSTGRES_PASSWORD: trusted_user_password
      POSTGRES_DB: test_db
